# Generated by Django 5.0.6 on 2024-07-01 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "max_players",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reservation_time",
                    models.CharField(
                        choices=[
                            ("10:00 - 12:00", "10:00 - 12:00"),
                            ("12:00 - 14:00", "12:00 - 14:00"),
                            ("14:00 - 16:00", "14:00 - 16:00"),
                            ("16:00 - 18:00", "16:00 - 18:00"),
                            ("18:00 - 20:00", "18:00 - 20:00"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField()),
                ("num_players", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.game",
                    ),
                ),
            ],
        ),
    ]
