# Generated by Django 5.0.6 on 2024-07-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_participant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="num_players",
        ),
    ]
