# Generated by Django 5.0.6 on 2024-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_remove_reservation_num_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="price",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
