# Generated by Django 5.0.6 on 2024-07-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_reservation_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="reservations.game",
            ),
        ),
    ]
